vlc:
  # CLI command to call VLC
  command: "C:\\Program Files (x86)\\VideoLAN\\VLC\\vlc.exe"
  http:
    # https://wiki.videolan.org/VLC_HTTP_requests/
    url: "http://localhost:8080/requests/status.xml"
    password: "XXXXXXXX"
  fullscreen: true
  playAndExit: true
server:
  port: 3000
  secure: false
  logLevel: "debug"
  dataFile: ".\\data.json"
client:
  downloadEnabled: true
  streamEnabled: true
  editApiSource: true
files:
  watch: true
  ignoreHidden: true
  # The locations of the video files
  locations:
    - folder: "E:\\Videos\\Anime"
      api: "mal"
    - folder: "C:\\Users\\MichaelSta\\Videos"
      api: "omdb"
api:
  omdb:
    enabled: false
    url: "http://www.omdbapi.com/"
    key: "XXXXXXXX"
  mal:
    enabled: false
    url: "https://myanimelist.net/"
    clientId: "XXXXXXXX"
    clientSecret: "XXXXXXXX"
  cacheDays: 30
